version: '2'
services: 
 mysql:
  tty: true
  image: mysql 
  ports: 
   - "3306:3306"
  command: --init-file /data/application/init.sql
  volumes:
        - ./Mysql/init.sql:/data/application/init.sql
  environment:
   - MYSQL_ROOT_PASSWORD=test
   - MYSQL_USER=test
   - MYSQL_PASSWORD=test
   - MYSQL_DATABASE=dev
 goapi:
  tty: true
  image: golang
  ports:
   - "82:82"
  links:
   - "mysql:mysql"
  volumes:
   - ./GoAPI:/app
  working_dir: /app
  entrypoint: sh -c "/app/up.sh"
  depends_on:
   - mysql
 vue_ui:
  tty: true
  image: node:lts-alpine
  volumes:
   - ./docker-vuejs:/app
  working_dir: /app
  entrypoint: sh -c "/app/up.sh"
  depends_on:
   - goapi
  ports:
   - "8080:8080"
  links:
   - "goapi:goapi"
   - "ai:ai"
 ai:
  tty: true
  image: tensorflow/tensorflow
  volumes:
   - ./AI:/app
  working_dir: /app
  entrypoint: sh -c "/app/up.sh"
  depends_on:
   - mysql 
  ports:
   - "5052:5052"
  links:
   - "mysql:mysql"

